# =============================================================================
# Patrik Persson, 2009
#
# Part of the SpeccyBoot project <http://speccyboot.sourceforge.net>
# =============================================================================

PREFIX     ?= /usr/local

BINDIR      = $(PREFIX)/bin
SCRIPTS     = speccyboot-update

install:
	install $(SCRIPTS) $(BINDIR)
